School-pws/Controllers/ApplicationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using School_pws.Data;
using School_pws.Helpers;
using School_pws.Models.Applications;
using System.Diagnostics;

namespace School_pws.Controllers
{
    public class ApplicationController : Controller
    {
        private readonly IApplicationRepository _applicationRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IConverterHelper _converterHelper;

        public ApplicationController(
            IApplicationRepository applicationRepository,
            ISubjectRepository subjectRepository,
            IConverterHelper converterHelper)
        {
            _applicationRepository = applicationRepository;
            _subjectRepository = subjectRepository;
            _converterHelper = converterHelper;
        }

        [Authorize]
        public async Task<IActionResult> Index()
        {
            var model = await _applicationRepository.GetApplicationsAsync(this.User.Identity.Name);
            return View(model);
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> Create()
        {
            var model = await _applicationRepository.GetApplicationDetails(this.User.Identity.Name);
            return View(model);
        }

        [Authorize(Roles = "Student")]
        public IActionResult AddSubject()
        {
            var model = new AddApplicationViewModel
            {
                Subjects = _subjectRepository.GetComboSubjects()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddSubject(AddApplicationViewModel model)
        {
            var response = await _applicationRepository.AddSubjectToApplication(model, this.User.Identity.Name);

            if (!response)
            {
                ModelState.AddModelError(string.Empty, "This subject is already in your application list or is already in another application.");
                model.Subjects = _subjectRepository.GetComboSubjects();
                return View(model);
            }

            return Redirect("Create");
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> AddGrade(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applicationDetail = await _applicationRepository.GetApplicationDetailsById(id);
            if (applicationDetail == null)
            {
                return NotFound();
            }

            var model = _converterHelper.ToAddGradeViewModel(applicationDetail);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddGrade(AddGradeViewModel model)
        {
            if (model == null)
            {
                return NotFound();
            }

            var applicationDetail = await _applicationRepository.GetApplicationDetailsById(model.Id);
            if (applicationDetail == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                applicationDetail.Grade = model.Grade;

                _applicationRepository.UpdateApplicationDetailsAsync(applicationDetail);

                return RedirectToAction("Details", new { id = applicationDetail.Application.Id }); ;
            }

            return View(model);
        }

        public async Task<IActionResult> DeleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _applicationRepository.DeleteSubjectFromApplication(id.Value);

            return RedirectToAction("Create");
        }

        public async Task<IActionResult> ConfirmApplication()
        {
            var response = await _applicationRepository.ConfirmApplicationAsync(this.User.Identity.Name);

            if (response)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Create");
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var application = await _applicationRepository.GetApplicationDetailsAsync(id);
            if (application == null)
            {
                return NotFound();
            }

            return View(application);
        }

        public async Task<IActionResult> AcceptApplication(int id)
        {
            var response = await _applicationRepository.AcceptApplication(id);

            if (response)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        public async Task<IActionResult> DenyApplication(int id)
        {
            var response = await _applicationRepository.DenyApplication(id);

            if (response)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

School-pws/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Core.Types;
using School_pws.Data;
using School_pws.Data.Entities;
using School_pws.Helpers;

namespace School_pws.Controllers
{
    public class SubjectController : Controller
    {
        private ISubjectRepository _subjectRepository;
        private readonly IUserHelper _userHelper;

        public SubjectController(
            ISubjectRepository subjectRepository,
            IUserHelper userHelper)
        {
            _subjectRepository = subjectRepository;
            _userHelper = userHelper;
        }

        public IActionResult Index()
        {
            return View(_subjectRepository.GetAll()
                .Where(s => s.IsActive == true)
                .OrderBy(s => s.Name));
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> MySubjects()
        {
            var subjects = await _subjectRepository.GetUserSubjectsAsync(User.Identity.Name);
            return View(subjects);
        }

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Manage()
        {
            return View(_subjectRepository.GetAll().OrderBy(s => s.Name));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _subjectRepository.GetByIdAsync(id.Value);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Subject subject)
        {
            if (ModelState.IsValid)
            {
                if (_subjectRepository.SubjectExistsByCode(subject.Code))
                {
                    ModelState.AddModelError("Code", "This code is already in use.");
                    return View(subject);
                }

                subject.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                await _subjectRepository.CreateAsync(subject);
                return RedirectToAction(nameof(Manage));
            }
            return View(subject);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _subjectRepository.GetByIdAsync(id.Value);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    subject.User = await _userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                    await _subjectRepository.UpdateAsync(subject);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _subjectRepository.ExistAsync(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Manage));
            }
            return View(subject);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _subjectRepository.GetByIdAsync(id.Value);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _subjectRepository.GetByIdAsync(id);

            if (subject == null)
            {
                return NotFound();
            }

            if (await _subjectRepository.HasDependenciesAsync(subject))
            {
                ViewBag.ErrorTitle = $"{subject.Name} is already in some application or in students subjects";
                ViewBag.ErrorMessage = $"{subject.Name} can not be deleted because there are applications or students subjects that contains it</br></br>";

                return View("Error");
            }

            await _subjectRepository.DeleteAsync(subject);
            return RedirectToAction(nameof(Manage));
        }

        public async Task<IActionResult> ActivateDesactivate(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _subjectRepository.ChangeActivedSubject(id);

            return RedirectToAction("Manage");
        }
    }
}

School-pws/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School_pws</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column min-vh-100 mb-0">
    <header class="mb-5">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 fixed-top">
            <div class="container-fluid">
                <b><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/schoolLogo.png" width="70px" height="70px" /></a></b>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Subject" asp-action="Index">Subjects</a>
                        </li>
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Application" asp-action="Index">Applications</a>
                            </li>
                        }
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Student"))
                        {
                            <a class="nav-link text-white" asp-area="" asp-controller="Subject" asp-action="MySubjects">My Subjects</a>

                        }
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle white text-white" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Subject" asp-action="Manage">Manage Subjects</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Manage">Manage Users</a></li>
                                </ul>
                            </li>
                        }
                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Employee"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    Employee
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Subject" asp-action="Manage">Manage Active Subjects</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Manage">Manage Students</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name <i class="fa-solid fa-user"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout">Logout <i class="fa-solid fa-right-from-bracket"></i></a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container pt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted p-4 mt-auto">
        <div class="container text-white">
            &copy; 2025 - School_pws - Privacy
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>